/**
 * Site footer: credits, links to the Uncertain Systems project, GitHub repo,
 * and the deployed Solana program id on the explorer.
 */
export function SiteFooter() {
  const PROGRAM_ID = "94Ja6Y8AuzmZHjQiyk2SzvoysnBr3F17nfHGrHm1idAZ";
  return (
    <footer className="site-footer">
      <div className="site-footer__inner">
        <div className="site-footer__col">
          <div className="site-footer__heading">About</div>
          <p className="site-footer__text">
            Dataprovider Staking is the on-chain settlement layer for the{" "}
            <a
              href="https://uncertain.systems/data-providers"
              target="_blank"
              rel="noopener noreferrer"
            >
              Uncertain Systems Data Provider Program
            </a>
            . Each approved provider gets a sponsored pump.fun token; holders
            stake it here to earn their proportional share of the revenue
            generated by the data that provider contributes to the GHC
            dataset.
          </p>
          <p className="site-footer__text">
            80% of creator fees flow to the provider&apos;s stakers. 20%
            routes to $UNSYS buybacks.
          </p>
        </div>

        <div className="site-footer__col">
          <div className="site-footer__heading">Links</div>
          <ul className="site-footer__list">
            <li>
              <a
                href="https://uncertain.systems"
                target="_blank"
                rel="noopener noreferrer"
              >
                Uncertain Systems
              </a>
            </li>
            <li>
              <a
                href="https://uncertain.systems/data-providers"
                target="_blank"
                rel="noopener noreferrer"
              >
                Data Provider Program
              </a>
            </li>
            <li>
              <a
                href="https://github.com/dncolomer/dataprovider_staking"
                target="_blank"
                rel="noopener noreferrer"
              >
                GitHub repository
              </a>
            </li>
            <li>
              <a
                href={`https://explorer.solana.com/address/${PROGRAM_ID}`}
                target="_blank"
                rel="noopener noreferrer"
              >
                Program on Solana Explorer
              </a>
            </li>
          </ul>
        </div>

        <div className="site-footer__col">
          <div className="site-footer__heading">Program</div>
          <p className="site-footer__text mono">{PROGRAM_ID}</p>
          <p className="site-footer__text muted" style={{ fontSize: "0.72rem" }}>
            Mainnet · Anchor 1.0 · Token-2022 compatible
          </p>
        </div>
      </div>

      <div className="site-footer__bottom">
        <span>
          © {new Date().getFullYear()} Uncertain Systems. No warranty. Use
          at your own risk.
        </span>
      </div>
    </footer>
  );
}
